package index

import "testing"

// Test and generated files bloat the index and pollute results without being
// what users search for (a k8s index was 40% generated conversion/deepcopy
// code). skipFile keeps them out.
func TestSkipFile(t *testing.T) {
	cases := []struct {
		name    string
		path    string
		content string
		skip    bool
	}{
		{"test file", "internal/foo_test.go", "package foo\n", true},
		{"normal go file", "internal/foo.go", "package foo\n\nfunc F() {}\n", false},
		{
			"generated header before package",
			"pkg/apis/zz_generated.deepcopy.go",
			"//go:build !ignore\n\n// Code generated by deepcopy-gen. DO NOT EDIT.\n\npackage v1\n",
			true,
		},
		{
			"do-not-edit after package is not the generated marker",
			"internal/bar.go",
			"package bar\n\n// Code generated here. DO NOT EDIT.\nfunc B() {}\n",
			false,
		},
		{
			"non-go file is never generated/test",
			"README.md",
			"# Code generated ... DO NOT EDIT.\n",
			false,
		},
	}
	for _, c := range cases {
		if got := skipFile(c.path, c.content); got != c.skip {
			t.Errorf("%s: skipFile = %v, want %v", c.name, got, c.skip)
		}
	}
}
