package lang

import (
	"strings"
	"testing"

	ts "github.com/tree-sitter/go-tree-sitter"
)

// TestPackQueriesCompile is the pack suite's most important test.
//
// A tree-sitter query that fails to compile does not crash anything: the
// chunker catches the error and degrades that language to blank-line splitting,
// for every file, forever. The failure is invisible in the output and shows up
// only as one language quietly scoring 15 points behind the others. This test
// caught exactly that — the TypeScript grammar names a class's name node
// `type_identifier` where JavaScript names it `identifier`, and one shared
// query for both dialects silently disabled TypeScript entirely.
func TestPackQueriesCompile(t *testing.T) {
	for _, p := range All() {
		if p.Grammar == nil {
			if p.Query != "" {
				t.Errorf("pack %s has a query but no grammar", p.Name)
			}
			continue
		}
		if p.Query == "" {
			t.Errorf("pack %s has a grammar but no query", p.Name)
			continue
		}
		q, err := ts.NewQuery(p.Grammar(), p.Query)
		if err != nil {
			t.Errorf("pack %s: query does not compile at offset %d: %s", p.Name, err.Offset, err.Message)
			continue
		}
		t.Cleanup(q.Close)

		// A query with no @chunk capture produces no chunks, which degrades to
		// the fallback just as silently as a compile error.
		if !hasCapture(q.CaptureNames(), "chunk") {
			t.Errorf("pack %s: query has no @chunk capture", p.Name)
		}
	}
}

func hasCapture(names []string, want string) bool {
	for _, n := range names {
		if n == want {
			return true
		}
	}
	return false
}

func TestEveryGrammarPackClaimsExtensions(t *testing.T) {
	for _, p := range All() {
		if len(p.Exts) == 0 {
			t.Errorf("pack %s claims no extensions", p.Name)
		}
		for _, e := range p.Exts {
			if !strings.HasPrefix(e, ".") || e != strings.ToLower(e) {
				t.Errorf("pack %s: extension %q must be lowercase and start with a dot", p.Name, e)
			}
			if got := ForPath("x" + e); got != p {
				t.Errorf("ForPath(x%s) = %v, want %s", e, got, p.Name)
			}
		}
	}
}

func TestIsTest(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		{"internal/chunk/ts.go", false},
		{"internal/chunk/ts_test.go", true},
		{"internal/chunk/testdata/sample.go", true},

		// Django's own django/test/ package is production code — the test
		// framework it ships. Only the plural convention marks a test subtree.
		{"django/test/client.py", false},
		{"django/tests/foo.py", true},
		{"django/db/models/query.py", false},
		{"tests/model_forms/models.py", true},
		{"django/utils/test_helper.py", true},

		{"packages/reactivity/src/effect.ts", false},
		{"packages/reactivity/src/effect.spec.ts", true},
		{"packages/reactivity/__tests__/effect.ts", true},

		{"crates/core/flags/hiargs.rs", false},
		{"tests/regression.rs", true},
		{"benches/bench.rs", true},

		{"src/main/java/org/example/App.java", false},
		{"src/test/java/org/example/AppTests.java", true},
		{"src/main/java/org/example/AppTest.java", true},

		{"src/t_string.c", false},
		{"src/t_string_test.c", true},
		{"db/version_set.cc", false},
		{"db/version_set_test.cc", true},

		{"README.md", false},
	}
	for _, c := range cases {
		if got := IsTest(c.path); got != c.want {
			t.Errorf("IsTest(%q) = %v, want %v", c.path, got, c.want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	if !IsGenerated("zz_generated.deepcopy.go", "// Code generated by deepcopy-gen. DO NOT EDIT.\n\npackage v1\n") {
		t.Error("Go generated header not recognized")
	}
	if IsGenerated("real.go", "// Package real does things.\n\npackage real\n") {
		t.Error("hand-written Go file reported as generated")
	}
	if !IsGenerated("api_pb2.py", "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n") {
		t.Error("protoc header not recognized")
	}
}
