package lang

import (
	ts "github.com/tree-sitter/go-tree-sitter"
	gogr "github.com/tree-sitter/tree-sitter-go/bindings/go"
)

// Go. Conventions: `foo_test.go` beside the code it tests, fixtures under
// `testdata/`, and the toolchain-standard generated-code header.
//
// Declaration groups (`const (...)`, `var (...)`, `type (...)`) are captured
// whole rather than per-spec: the members of a group are written together
// because they mean something together, and splitting them is the classic way
// to lose an enum's meaning.
var Go = &Pack{
	Name:             "go",
	Exts:             []string{".go"},
	TestBases:        []string{"*_test.go"},
	TestDirs:         []string{"testdata"},
	GeneratedMarkers: []string{"Code generated by", "Code generated "},
	Grammar:          func() *ts.Language { return ts.NewLanguage(gogr.Language()) },
	Query: `
(function_declaration name: (identifier) @name body: (block) @body) @chunk
(method_declaration
  receiver: (parameter_list (parameter_declaration
    type: [(type_identifier) @qualifier (pointer_type (type_identifier) @qualifier)]))
  name: (field_identifier) @name body: (block) @body) @chunk
(type_declaration (type_spec name: (type_identifier) @name)) @chunk
(const_declaration (const_spec name: (identifier) @name)) @chunk
(var_declaration (var_spec name: (identifier) @name)) @chunk
`,
}

func init() { Register(Go) }
