package lang

import (
	ts "github.com/tree-sitter/go-tree-sitter"
	rsgr "github.com/tree-sitter/tree-sitter-rust/bindings/go"
)

// Rust. Integration tests live in a crate-level `tests/` directory and
// benchmarks in `benches/`; unit tests live in-file behind `#[cfg(test)]`,
// which file-level classification cannot see. The query's @drop pattern removes
// those modules instead — without it a Rust crate's index is a third test code,
// and `mod tests` blocks crowd out the implementations they exercise.
//
// `impl` blocks are scopes, not chunks: an impl's methods are the retrievable
// units, and the impl contributes the type name that makes `new` mean
// `Parser.new`.
var Rust = &Pack{
	Name:             "rust",
	Exts:             []string{".rs"},
	TestBases:        []string{"*_test.rs", "tests.rs"},
	TestDirs:         []string{"tests", "benches"},
	GeneratedMarkers: []string{"@generated", "DO NOT EDIT", "Generated by"},
	AttachKinds:      []string{"attribute_item"},
	Grammar:          func() *ts.Language { return ts.NewLanguage(rsgr.Language()) },
	Query: `
(function_item name: (identifier) @name body: (block) @body) @chunk
(struct_item name: (type_identifier) @name) @chunk
(enum_item name: (type_identifier) @name) @chunk
(union_item name: (type_identifier) @name) @chunk
(type_item name: (type_identifier) @name) @chunk
(const_item name: (identifier) @name) @chunk
(static_item name: (identifier) @name) @chunk
(macro_definition name: (identifier) @name) @chunk

(trait_item name: (type_identifier) @name body: (declaration_list) @body) @scope
(impl_item type: (type_identifier) @name body: (declaration_list) @body) @scope
(impl_item type: (generic_type type: (type_identifier) @name) body: (declaration_list) @body) @scope
(mod_item name: (identifier) @name body: (declaration_list) @body) @scope

(source_file (attribute_item) @attr . (mod_item) @drop
  (#match? @attr "cfg\\(test\\)"))
(declaration_list (attribute_item) @attr . (mod_item) @drop
  (#match? @attr "cfg\\(test\\)"))
`,
}

func init() { Register(Rust) }
