package lang

import (
	"strings"

	ts "github.com/tree-sitter/go-tree-sitter"
	cgr "github.com/tree-sitter/tree-sitter-c/bindings/go"
	cppgr "github.com/tree-sitter/tree-sitter-cpp/bindings/go"
)

// C and C++ are separate grammars but share their file conventions. Headers are
// the interesting asymmetry: `.hpp`/`.hh`/`.hxx` are unambiguously C++, while
// `.h` is claimed by C and re-routed to C++ per file by cppHeader below.
//
// In C the aggregate types are chunks; in C++ they are scopes, because a C++
// class carries method definitions that deserve their own chunks and a
// namespace should qualify everything inside it rather than swallow it.
var (
	C = &Pack{
		Name:             "c",
		Exts:             []string{".c", ".h"},
		Disambiguate:     cppHeader,
		TestBases:        []string{"*_test.c", "test_*.c", "*_tests.c"},
		TestDirs:         cTestDirs,
		GeneratedMarkers: cGenerated,
		Grammar:          func() *ts.Language { return ts.NewLanguage(cgr.Language()) },
		Query: `
(function_definition
  declarator: (function_declarator declarator: (identifier) @name)
  body: (compound_statement) @body) @chunk
(function_definition
  declarator: (pointer_declarator declarator: (function_declarator declarator: (identifier) @name))
  body: (compound_statement) @body) @chunk
(type_definition declarator: (type_identifier) @name) @chunk
(struct_specifier name: (type_identifier) @name body: (field_declaration_list)) @chunk
(union_specifier name: (type_identifier) @name body: (field_declaration_list)) @chunk
(enum_specifier name: (type_identifier) @name body: (enumerator_list)) @chunk
(preproc_function_def name: (identifier) @name) @chunk
`,
	}
	Cpp = &Pack{
		Name: "cpp",
		Exts: []string{".cc", ".cpp", ".cxx", ".hpp", ".hh", ".hxx"},
		TestBases: []string{
			"*_test.cc", "*_test.cpp", "*_unittest.cc", "*_unittest.cpp",
			"test_*.cc", "test_*.cpp",
		},
		TestDirs:         cTestDirs,
		GeneratedMarkers: cGenerated,
		WrapKinds:        []string{"template_declaration"},
		Grammar:          func() *ts.Language { return ts.NewLanguage(cppgr.Language()) },
		Query: `
(function_definition
  declarator: (function_declarator
    declarator: [(identifier) (field_identifier) (qualified_identifier) (destructor_name) (operator_name)] @name)
  body: (compound_statement) @body) @chunk
(function_definition
  declarator: (pointer_declarator declarator: (function_declarator
    declarator: [(identifier) (field_identifier) (qualified_identifier)] @name))
  body: (compound_statement) @body) @chunk
(function_definition
  declarator: (reference_declarator (function_declarator
    declarator: [(identifier) (field_identifier) (qualified_identifier)] @name))
  body: (compound_statement) @body) @chunk
(type_definition declarator: (type_identifier) @name) @chunk
(alias_declaration name: (type_identifier) @name) @chunk
(enum_specifier name: (type_identifier) @name body: (enumerator_list)) @chunk

(namespace_definition name: (namespace_identifier) @name body: (declaration_list) @body) @scope
(class_specifier name: (type_identifier) @name body: (field_declaration_list) @body) @scope
(struct_specifier name: (type_identifier) @name body: (field_declaration_list) @body) @scope
`,
	}
)

// cppHeader sends a `.h` file to the C++ pack when it uses a construct C does
// not have. LevelDB is the motivating corpus: every one of its headers is
// `.h`, every one of them is C++, and under the C grammar its template classes
// parse into nonsense — `SkipList` disappears entirely and its methods are
// reported as free functions with spans covering half the file.
//
// The markers are deliberately unambiguous. `class`, `namespace`, `template<`
// and `::` cannot appear in valid C outside a string or comment, and a stray
// occurrence inside one only costs a C header the C++ grammar, which parses C
// correctly anyway. The reverse mistake is the expensive one.
func cppHeader(content string) string {
	for _, marker := range []string{"\nclass ", "\nnamespace ", "template <", "template<", "::", "\npublic:", "extern \"C\""} {
		if strings.Contains(content, marker) {
			return "cpp"
		}
	}
	return ""
}

var (
	cTestDirs  = []string{"tests"}
	cGenerated = []string{"@generated", "DO NOT EDIT", "Generated by the protocol buffer compiler", "automatically generated"}
)

func init() {
	Register(C)
	Register(Cpp)
}
