package lang

import (
	ts "github.com/tree-sitter/go-tree-sitter"
	pygr "github.com/tree-sitter/tree-sitter-python/bindings/go"
)

// Python. Note the deliberate absence of "test" (singular) from TestDirs:
// Django's own `django/test/` package is production code — the test *framework*
// it ships — and excluding it would silently delete a real subsystem from the
// index. Only the plural `tests/` convention marks a test subtree.
//
// The query captures functions only where they are declarations a reader would
// name: at module level and in a class body. A closure defined inside a
// function stays part of that function's chunk, which is where it is
// understood.
var Python = &Pack{
	Name:             "python",
	Exts:             []string{".py", ".pyi"},
	TestBases:        []string{"test_*.py", "*_test.py", "conftest.py"},
	TestDirs:         []string{"tests"},
	GeneratedMarkers: []string{"@generated", "DO NOT EDIT", "Generated by the protocol buffer compiler"},
	// A decorator is a child of decorated_definition, so it reaches a class
	// through the sibling walk rather than through a wrapper rule.
	AttachKinds: []string{"decorator"},
	Grammar:     func() *ts.Language { return ts.NewLanguage(pygr.Language()) },
	Query: `
(module (function_definition name: (identifier) @name body: (block) @body) @chunk)
(module (decorated_definition definition: (function_definition name: (identifier) @name body: (block) @body)) @chunk)
(class_definition body: (block (function_definition name: (identifier) @name body: (block) @body) @chunk))
(class_definition body: (block (decorated_definition definition: (function_definition name: (identifier) @name body: (block) @body)) @chunk))
(class_definition name: (identifier) @name body: (block) @body) @scope
`,
}

func init() { Register(Python) }
